### ISSUE TITLE
Doesn't seem to work with Server side rendering

### ISSUE THREAD

**Issue by Jaikant** [Astrocoders/react-image-smooth-loading#50]
I have been trying to use it with SSR, but it doesn't work.

**Comment by fakenickels** [comment]
Maybe it's because of the componentDidMount hook.
Are you trying to use webpacks SSR?

**Comment by fakenickels** [comment]
Maybe solved now by https://github.com/Astrocoders/react-image-smooth-loading/releases/tag/v2.0.0
