### ISSUE TITLE
Image placeholder does not disappear

### ISSUE THREAD

**Issue by rrsilaya** [Astrocoders/react-image-smooth-loading#51]
The default image placeholder does not disappear even if the images are loaded.

**Comment by guilhermedecampo** [comment]
Can you provide more information on how you used the component?

**Comment by rrsilaya** [comment]
I used it as is. Imported it with `import Img from 'react-image-smooth-loading'` then `<Img src={img} />`. What happens is, the placeholder stays visible even if the images are loaded.

**Comment by fakenickels** [comment]
Are you sure that the var `img` is defined?
What is your use case?

**Comment by rrsilaya** [comment]
Yes, it is defined. The image is showing properly but the placeholder is still visible even if the image is loaded.

**Comment by guilhermedecampo** [comment]
Hmm seems that your image has transparency. Is that true?

**Comment by rrsilaya** [comment]
No, the image does not have transparency. The placeholder image is placed below the loaded image itself.

**Comment by fakenickels** [comment]
Ah, so I think the component style isn't been passed down to your usage.
Are you using webpack?

**Comment by rrsilaya** [comment]
I'm using `create-react-app`. Is that a problem?

**Comment by fakenickels** [comment]
That might be the problem indeed, this package makes heavy use of css-modules.
But I have in mind to change it to styled-components. 
Try importing it like this and let me know if it works
```js
import Image from 'react-image-smooth-loading/dist/browser'
```

**Comment by fakenickels** [comment]
But it does need an update to the current React API

**Comment by rrsilaya** [comment]
It throws an error `TypeError: Cannot read property 'createClass' of undefined` and fails.

If you're interested in how it looks, here it is:
![screenshot](https://i.imgur.com/gxipP80.png)

**Comment by guilhermedecampo** [comment]
oh lord! After this image we will need to fix it @grsabreu haha 🐶

**Comment by fakenickels** [comment]
yes, as I was thinking
the styles aren't being loaded correctly
I already started rewriting with styled-components

**Comment by fakenickels** [comment]
yes @guilhermedecampo haha

**Comment by PascalPixel** [comment]
Looking forward to it @grsabreu

**Comment by fakenickels** [comment]
Solved by https://github.com/Astrocoders/react-image-smooth-loading/releases/tag/v2.0.0

**Comment by acomito** [comment]
i'm not sure if I'm having a similar issue. My images a loading correctly, they fade in and the placeholder disappears.  But if I right click "open in new tab", the image that open is the placeholder.

**Comment by fakenickels** [comment]
@acomito that is because the placeholder keeps above the image and with the opacity 0, it isn't removed from the DOM
