### ISSUE TITLE
How to handle in infinite loading list? On loading more, the images already loaded will fire a fade in.

### ISSUE THREAD

**Issue by acomito** [Astrocoders/react-image-smooth-loading#53]
Great package. I have an issue where a list is loaded, the user scrolls to the bottom, more images are loaded, and the entire list re-renders. This typically isn't noticeable, but in this case the fade is re-firing for all the images, not just the newly loaded images. Does that make sense?

Maybe somewhere in componentShouldUpdate or one of the other lifecycle events? Or track it in local state? I admittedly didn't look into the source code yet...

**Comment by fakenickels** [comment]
You can wrap the Image component in a HoC that prevents the component from rendering again.
But if you are using a list, using a unique `key` prop for each Image should have been enough.
If even having a unique prop for each Image does not solve the problem, use the HoC solution. We can take a look on recompose's ones:
https://github.com/acdlite/recompose/blob/master/docs/API.md#shouldupdate

**Comment by acomito** [comment]
Yeah I do have a unique key. I'll check out using recompose and report back. Thanks @grsabreu

**Comment by fakenickels** [comment]
did it worked @acomito ?

**Comment by acomito** [comment]
@grsabreu I actually didn't bother setting up recompose to try. But I closed the issue because I figured the issue was outside the realm of your lib.
