### ISSUE TITLE
imgClasses not working 

### ISSUE THREAD

**Issue by mighty-potato** [Astrocoders/react-image-smooth-loading#54]
I had tried input imgClasses both as string and array both not showing when it compiled and i tired to look at the code i see that the props.imgClasses was never convert to className

**Comment by mighty-potato** [comment]
found it i have to use imageProps instead and put className as object i think the documentation was out of dated

**Comment by fakenickels** [comment]
Indeed, good catch! Thx
Fixed in https://github.com/Astrocoders/react-image-smooth-loading/commit/aed74425d6fa36dee907b785b7f7e4221b753332
