### ISSUE TITLE
Is there a way to pass "alt" property to img

### ISSUE THREAD

**Issue by diegohaz** [Astrocoders/react-image-smooth-loading#6]
And other properties

**Comment by psimyn** [comment]
not currently, props need to be added to `lib/index.js`

example https://github.com/Astrocoders/react-image-smooth-loading/pull/7/files#diff-6d186b954a58d5bb740f73d84fe39073R18

**Comment by fakenickels** [comment]
Seems a fair feature! I'm going to merge @psimyn PR soon.

**Comment by guilhermedecampo** [comment]
👍

**Comment by fakenickels** [comment]
Gonna be shipped on the next release

**Comment by fakenickels** [comment]
https://github.com/Astrocoders/react-image-smooth-loading/releases/tag/v1.0.7
Shipped
